### ISSUE TITLE
Pokerstars bug

### ISSUE THREAD

**Issue by carlitoselmago** [dickreuter/Poker#46] opened 2017-06-03 09:12 UTC
I get this error in the terminal when playing pokerstars, I don't know if it's simply a performance issue since Pokerstars runs way slower than PartyPoker. The AI gets stucked before the betting/decission time runs out.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "Poker\main.py", line 149, in run
  File "table_analysers\table_screen_based.py", line 435, in get_other_player_status
  File "table_analysers\table_screen_based.py", line 387, in get_bot_pot
IndexError: list index out of range

**Comment by dickreuter** [comment] 2017-06-03 10:15
Pokerstars implementation is not finished. I can finish it if somebody
borrows me an account or send me screenshots. It won't take much longer
than 2-3 hours to finish it. For now use partypoker.

**Comment by carlitoselmago** [comment] 2017-06-03 10:34
Oh, sorry, I didn't understood well that part. Actually I've been working on a computer vision class for pokerstars till I end up in this project and realised how well this is made compared to my project. 
Since I've been working on Pokerstars game recognition I'm sending you some usefull assets by email. Hope they are useful.

**Comment by dickreuter** [comment] 2017-06-03 10:45
great will have a look the next few days and try to implement it. That will
definitely be useful.

**Comment by lindak99** [comment] 2017-10-10 15:30
I have the same problem. Is it a solution? Thanks

**Comment by dickreuter** [comment] 2017-10-10 15:39
Can you send me a screenshot? It should have saved one automatically in the
folder. I can then fix it. Tx

**Comment by lindak99** [comment] 2017-10-10 16:52
![3](https://user-images.githubusercontent.com/20097023/31398944-eef7d800-adea-11e7-9e68-341de3b03624.png)

![oowf](https://user-images.githubusercontent.com/20097023/31398841-92fdbef2-adea-11e7-9080-533d88114ee3.png)

**Comment by dickreuter** [comment] 2017-10-10 16:54
I need the screenshot png file that shows the table

**Comment by lindak99** [comment] 2017-10-10 17:01
This one
![screenshot_vbox](https://user-images.githubusercontent.com/20097023/31399615-32c8da0a-aded-11e7-860f-17c59b37fb88.png)

**Comment by dickreuter** [comment] 2017-10-10 17:10
There should be another png file, possibly in the /log folder. Also the
errors.log would be helpful.

**Comment by lindak99** [comment] 2017-10-10 17:40
I started the program again. 
[errors.log](https://github.com/dickreuter/Poker/files/1372819/errors.log)
![347479325_preflop_0](https://user-images.githubusercontent.com/20097023/31401279-ba42c2fc-adf2-11e7-89f7-fb4079993e48.png)
![Uploading 12385845_PreFlop_0.png…]()

**Comment by dickreuter** [comment] 2017-10-10 21:47
The error is caused by missing values of the coordindates file. Can you
send me a screenshot of an example where you put something into the pot
(i.e. after a call or a raise)? I can then fix it. regards

**Comment by lindak99** [comment] 2017-10-10 22:50
[https://ctrlv.cz/shots/2017/10/11/1mZU.png](url)

Is this error ok?  _table - ERROR - Could not determine dealer position. Assuming UTG_

**Comment by dickreuter** [comment] 2017-10-12 09:16
Any chance you can upload another screenshot where 5 cards are visible on the table on the river? I can then make it work with the new neural network interface for pokerstars as well.

**Comment by snarb** [comment] 2017-10-12 12:06
@dickreuter are you banned at poker-stars? :) If it's not a secret - what was your mistake how did they ban you?

**Comment by dickreuter** [comment] 2017-10-12 16:52
Yes got a lifetime ban. I wasn’t using VM and VPN.

**Comment by dickreuter** [comment] 2017-10-12 23:25
This issue is now resolved and a new binary version will be released soon.

**Closed by dickreuter** 2017-10-12 23:25 UTC
